<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>LampaWin</AssemblyName>
    <RootNamespace>LampaWin.Desktop</RootNamespace>
    <Version>2.0.0.1</Version>
    <AssemblyVersion>2.0.0.1</AssemblyVersion>
    <FileVersion>2.0.0.1</FileVersion>
    <InformationalVersion>2.0.0b</InformationalVersion>
    <ReleaseVersion>2.0.0b</ReleaseVersion>
    <ApplicationIcon>Assets\LampaWin.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\LampaWin.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LampaWin.Core\LampaWin.Core.csproj" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4258.31" />
    <PackageReference Include="LibVLCSharp.WPF" Version="3.10.1" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.24" />
  </ItemGroup>
</Project>
